# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.2
_src_path: gh:ThatXliner/pyt2
add_docs: true
author: Bryan Hu
email: thatxliner@gmail.com
is_app: false
module_name: data49
project_description: A gold rush-themed data mining library
project_name: Data49
pypi_name: data49
username: ThatXliner
